steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'lol', '.']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'lol']
options:
  machineType: 'N1_HIGHCPU_8'
timeout: 660s
tags: ['mytag1', 'mytag2']